import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.figure import Figure
from collections import Counter
from typing import Tuple, List, Dict


def save_df_to_csv(df: pd.DataFrame, csv_path: str):
    """
    Saves a pandas DataFrame to a CSV file.

    Args:
        csv_path (str): CSV path.
        df (pd.DataFrame): DataFrame containing the data.
    """
    df.to_csv(csv_path, index=False)
    print(f"File saved: {csv_path}")


def save_plot_to_png(fig: Figure, image_path: str, dpi: int = 300):
    """
    Saves a Matplotlib figure as a PNG image with a specified resolution.

    Args:
        fig (matplotlib.figure.Figure): The Matplotlib figure object to be
        saved.
        image_path (str): The full file path (including filename) where the
        image will be saved.
        dpi (int): The image resolution in dots per inch (DPI). Higher values
        produce better quality but larger file sizes.
    """
    fig.savefig(image_path, dpi=dpi, bbox_inches='tight')
    plt.close(fig)
    print(f"Image saved: {image_path}")


def preprocess_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """
    Cleans and standardizes numeric columns in a DataFrame generated by
    `prediction_and_att_weights.py` or `extract_attention_weights.py`.

    This function converts string-based numeric columns (e.g., those containing
    commas instead of dots as decimal separators) into proper numeric types.
    Only columns whose names contain "weight" or "inference" are processed.

    Args:
        df (pd.DataFrame): The input DataFrame containing prediction or
            attention weight data.

    Returns:
        pd.DataFrame: The processed DataFrame with standardized numeric
        columns. Non-numeric or invalid values are coerced to NaN.
    """
    for col in df.columns:
        if ("weight" in col or "inference" in col) and \
                df[col].dtype == "object":
            df[col] = df[col].astype(str).str.replace(
                ',', '.', regex=False)
            df[col] = pd.to_numeric(df[col], errors='coerce')

    return df


def create_unique_product_names(df: pd.DataFrame) -> pd.DataFrame:
    """
    Generates unique product names by combining sequence and product
    information.

    This function scans through sequence/product column pairs
    (e.g., seq1/product1, seq2/product2, ..., seq5/product5) and creates
    distinct product identifiers for each sequence-product combination. It
    appends a numeric suffix to duplicate product names associated with
    different sequences, ensuring that each (sequence, product) pair has a
    unique name.

    The renaming is performed in-place on a copy of the original DataFrame.

    Args:
        df (pd.DataFrame): Input DataFrame containing columns named as
            pairs of "seqN" and "productN" (where N ranges from 1 to 5).
            Missing columns are ignored.

    Returns:
        pd.DataFrame: A copy of the original DataFrame with updated product
        names, where duplicate names are made unique by appending an index
        (e.g., "productA_1", "productA_2").
    """
    df_copy = df.copy()
    pairs = [(f"seq{i}", f"product{i}") for i in range(1, 6)]

    df_long = pd.concat(
        [df_copy[[seq_col, prod_col]].rename(
            columns={seq_col: "seq", prod_col: "product"}
        ) for seq_col, prod_col in pairs if seq_col in df_copy.columns
            and prod_col in df_copy.columns],
        ignore_index=True).dropna()

    df_long["product_num"] = df_long.groupby(
        "product")["seq"].transform(lambda x: pd.factorize(x)[0] + 1)
    df_long["product_renamed"] = df_long["product"] + \
        "_" + df_long["product_num"].astype(str)

    rename_map = dict(
        zip(zip(df_long["seq"], df_long["product"]),
            df_long["product_renamed"]))

    for seq_col, prod_col in pairs:
        if seq_col in df_copy.columns and prod_col in df_copy.columns:
            df_copy.loc[:, prod_col] = df_copy.apply(
                lambda row: rename_map.get(
                    (row[seq_col], row[prod_col]), row[prod_col]
                ), axis=1
            )
    return df_copy


def unpivot_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """
    Transforms a wide-format DataFrame containing multiple product and weight
    columns into a long (tidy) format for analysis.

    This function handles DataFrames with up to 5 product/weight pairs
    (columns named 'product1'...'product5' and 'weight1'...'weight5')
    alongside identifier columns ['model', 'id', 'inference', 'prediction',
    'label', 'match'].

    For each product/weight pair, a temporary DataFrame is created, renaming
    the columns to 'product' and 'weight', and then all pairs are concatenated
    into a single long-format DataFrame. Rows with missing 'product' values are
    dropped.

    Args:
        df (pd.DataFrame): Input DataFrame in wide format, containing
        identifier columns and up to five product/weight column pairs.

    Returns:
        pd.DataFrame: Long-format DataFrame with columns:
            - 'model', 'id', 'inference', 'prediction', 'label', 'match'
            - 'product': product name from the original wide columns
            - 'weight': corresponding weight for the product
        Rows are stacked such that each product/weight pair becomes a separate
        row, and rows with missing 'product' are removed. The index is reset.
    """
    id_vars = ['model', 'id', 'inference', 'prediction', 'label', 'match']

    melted_dfs = []
    for i in range(1, 6):
        product_col = f'product{i}'
        weight_col = f'weight{i}'
        temp_df = df[id_vars + [product_col, weight_col]].rename(
            columns={product_col: 'product', weight_col: 'weight'})
        melted_dfs.append(temp_df)

    unpivoted_df = pd.concat(
        melted_dfs, ignore_index=True).dropna(subset=['product'])
    unpivoted_df.reset_index(drop=True, inplace=True)
    return unpivoted_df


def get_top_products_and_weights_df(
        data_subset: pd.DataFrame,
        num_products: int = 20) -> Tuple[pd.DataFrame, List[str]]:
    """
    Extracts the top N most frequent products from a dataset and returns a
    long-form DataFrame suitable for visualization.

    This function identifies the most frequent products across columns
    'product1' to 'product5', selects the top N products by frequency, and
    reshapes the data into a long format containing 'product' and 'weight'
    columns. Only non-null weights for the top products are included.

    Args:
        data_subset (pd.DataFrame): Input DataFrame containing product columns
            ('product1' to 'product5') and their corresponding weight columns
            ('weight1' to 'weight5').
        num_products (int, optional): Number of top products to select based on
            frequency. Defaults to 20.

    Returns:
        Tuple[pd.DataFrame, List[str]]: Tuple with Long-format DataFrame with
        columns:
            - 'product': Name of the product (from top N most frequent);
            - 'weight': Corresponding weight value.
        And a list of top N product names in order of decreasing frequency.
    """
    product_cols = [f'product{i}' for i in range(1, 6)]
    all_products = []
    for col in product_cols:
        all_products.extend(data_subset[col].dropna().tolist())

    product_counts = Counter(all_products)
    top_products_list = [prod for prod,
                         _ in product_counts.most_common(num_products)]
    top_products_set = set(top_products_list)

    long_data = []
    for _, row in data_subset.iterrows():
        for i in range(1, 6):
            product = row.get(f'product{i}')
            if product in top_products_set:
                weight = row.get(f'weight{i}')
                if pd.notna(weight):
                    long_data.append({'product': product, 'weight': weight})

    return pd.DataFrame(long_data), top_products_list


def get_top_products_and_avg_weights(
        data_subset: pd.DataFrame,
        num_products: int = 20) -> Dict[str, np.float64]:
    """
    Identifies the top N most frequent products and calculates their average
    weights.

    This function scans the product columns ('product1' to 'product5') in the
    input DataFrame, counts the frequency of each product, selects the top N
    products, and computes the average weight for each. Only non-null weight
    values are considered in the calculation.

    Args:
        data_subset (pd.DataFrame): Input DataFrame containing product columns
            ('product1' to 'product5') and corresponding weight columns
            ('weight1' to 'weight5').
        num_products (int, optional): Number of top products to select based
            on frequency. Defaults to 20.

    Returns:
        Dict[str, float]: Dictionary mapping each of the top N product names to
        its average weight. Products without any valid weights are excluded.
    """
    product_cols = [f'product{i}' for i in range(1, 6)]
    all_products = []
    for col in product_cols:
        all_products.extend(data_subset[col].dropna().tolist())

    product_counts = Counter(all_products)
    top_products = [prod for prod,
                    _ in product_counts.most_common(num_products)]

    product_weights = {prod: [] for prod in top_products}
    for _, row in data_subset.iterrows():
        for i in range(1, 6):
            product = row.get(f'product{i}')
            if product in product_weights:
                weight = row.get(f'weight{i}')
                if pd.notna(weight):
                    product_weights[product].append(weight)

    avg_weights = {prod: np.mean(weights) for prod,
                   weights in product_weights.items() if weights}
    return avg_weights


def get_top_products_and_counts(
        data_subset: pd.DataFrame,
        num_products: int = 20) -> Dict[str, int]:
    """
    Identifies the top N most frequent products and returns their occurrence
    counts.

    This function examines product columns ('product1' to 'product5') in the
    input DataFrame, counts the occurrences of each product across all rows,
    and selects the top N products by frequency.

    Args:
        data_subset (pd.DataFrame): Input DataFrame containing product columns
            ('product1' to 'product5').
        num_products (int, optional): Number of top products to select based
            on frequency. Defaults to 20.

    Returns:
        Dict[str, int]: Dictionary mapping each of the top N product names
                        to its count of occurrences.
    """
    product_cols = [f'product{i}' for i in range(1, 6)]
    all_products = []
    for col in product_cols:
        all_products.extend(data_subset[col].dropna().tolist())

    product_counts = Counter(all_products)
    top_products_with_counts = product_counts.most_common(num_products)
    return dict(top_products_with_counts)


def get_top_products_by_avg_weight(
    data_subset: pd.DataFrame,
        num_products: int = 5) -> Tuple[pd.DataFrame, List[str]]:
    """
    Identifies the top N products with the highest average weight.

    This function unpivots product/weight column pairs ('product1'-'product5'
    and 'weight1'-'weight5') into a long-format DataFrame, computes the average
    weight for each product, and selects the top N products by average weight.
    It returns both the filtered long-format DataFrame containing only the top
    products and a list of the top product names.

    Args:
        data_subset (pd.DataFrame): Input DataFrame containing product columns
            ('product1' to 'product5') and their corresponding weight columns
            ('weight1' to 'weight5').
        num_products (int, optional): Number of top products to select based on
            average weight. Defaults to 5.

    Returns:
        Tuple[pd.DataFrame, List[str]]: Tuple with Long-format DataFrame with
        columns 'product' and 'weight', containing only rows for the top N
        products and List of top N product names, sorted by descending average
        weight.
    """
    melted_dfs = []
    for i in range(1, 6):
        product_col = f'product{i}'
        weight_col = f'weight{i}'
        temp_df = data_subset[[product_col, weight_col]].rename(
            columns={product_col: 'product', weight_col: 'weight'})
        melted_dfs.append(temp_df)

    unpivoted_df = pd.concat(
        melted_dfs, ignore_index=True).dropna(subset=['product'])

    # Calculate average weight per product
    product_avg_weights = unpivoted_df.groupby(
        'product')['weight'].mean().reset_index()

    # Sort by average weight and get the top N
    top_products_df = product_avg_weights.sort_values(
        by='weight', ascending=False).head(num_products)

    # Filter the original unpivoted df to get only the top products
    top_products_list = top_products_df['product'].tolist()
    top_products_data = unpivoted_df[unpivoted_df['product'].isin(
        top_products_list)]

    return top_products_data, top_products_list
